language: python
python:
- 3.5
services: postgresql
env:
  global:
  - TRAVIS_CI='true'
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - PYTHONPATH="/home/travis/build/hongmeiq/django_tdd"
  - DATABASE_URL='postgres://postgres:@localhost:5432/travisdb'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - coverage run --source lists,superlists --branch --omit */migrations/*,*/tests/*,*/functional_tests/* manage.py test
# after_success:
#   - coveralls
notifications:
  email:
    on_success: change
    on_failure: change

