language: python
python:
- 3.5
services: postgresql
env:
  global:
  - TRAVIS_CI='true'
  - DJANGO_SETTINGS_MODULE="superlists.settings"
  - PYTHONPATH="/home/travis/build/hongmeiq/django_tdd"
  - DATABASE_URL='postgres://postgres:@localhost:5432/travisdb'
install:
- pip install -r requirements.txt
- pip install coveralls
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
- phantomjs django_tdd/staticfiles/tests/runner.js django_tdd/staticfiles/tests/tests.html
- coverage run --source lists,superlists --branch --omit */migrations/*,*/tests/*,*/functional_tests/*
  manage.py test
after_success:
- coveralls
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: 1IpW2kKQbJW+UuznRTDSwZVvLAk3En8CjJDahFyPhXEXrVKXXNtIe6qVPpbvQYARFIgsyFvDkYK47yMbKzFpa/EI2ghwIjFwv6e+xWT+EY+wwgEr4v1hGAlKFnGK12t5oNtkELsaBRjuVHBefaKm4PfM/QhAveUc2Bi91/5sBa17Ed/GBKGj+M689kqmyEJhhjrgWx+wkROcgbAmplbmV+YdgOC1dEKl/SUJT8d00TgoFW3skPrHssFUyjdt/Z8MRsc520fCTTBPRQetVeZ2TjSayFmSKPPp6wcHU11NAY0hYOBtA1FiMrD2HV5oAq3aFbgePKkuotCKApIKWEX9nzdgHD8cG7wz7Evjo7gv54WUCjpIblVNcEakYTxNNS1kxARPf6Bu2Hf4j0k3IbQoUsGCQknuTteI4AcB7vXh/8Yq2Wer7zv1EJeRHkVrmSddzsFULXWjjfz/12wezcFHeYsBEvgnCP0bCmFdo64oYADrB67QgH6EKXmE3K+YvW3qufkkhtqcFecyY4m5VZUdSO/JRCaBdS4hN94Pw3Q6/kzbfiKbbuM6ZE7KZAouHZji8MjD2ex0zLbGcB68rLioBaEoYVHUUR3Q8jPOsVMYi0OIvCtwbh76ZjKoA9LAL1TS6hc50jYi24ne0dTll+LKdi5sAzwskPdKWgqFsnRGPf4=
  app: warm-taiga-9743
  on:
    repo: hongmeiq/django_tdd
